general.import = ["./themes/everforest-dark.toml"]

[window]
opacity = 0.9
blur = true
padding.x = 15
padding.y = 20
decorations = "None"

[font]
size = 10
normal.family = "CaskaydiaCove Nerd Font"
bold.family = "CaskaydiaCove Nerd Font"
italic.family = "CaskaydiaCove Nerd Font"
bold_italic.family = "CaskaydiaCove Nerd Font"

[scrolling]
history = 50000
multiplier = 5

[cursor]
style.shape = "Block"
style.blinking = "On"
blink_interval = 800
blink_timeout = 10

[mouse]
hide_when_typing = true

