preload = $HOME/Dotfiles/wallpapers/art/jan-stanislawski/dusk.jpg

wallpaper {
    monitor = eDP-1
    path = $HOME/Dotfiles/wallpapers/art/jan-stanislawski/dusk.jpg
    fit_mode = cover
}
splash = false
