general {
    # avoid starting multiple hyprlock instances.
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    # Time in seconds
    timeout = 600
    # lock screen when timeout has passed
    on-timeout = loginctl lock-session 
}

listener {
    # Time in seconds
    timeout = 630
    # screen off when timeout has passed
    on-timeout = hyprctl dispatch dpms off
    # screen on when activity is detected after timeout has fired.
    # System -> Source Detection -> Manual
    on-resume = hyprctl dispatch dpms on 
}
